version: '3'

services:
  ledfx:
    image: ledfx:latest
    container_name: ledfx
    build:
      context: .
    environment: 
      - HOST=host.docker.internal
    ports:
      - 8888:8888
    volumes:
      - ~/ledfx-config:/app/ledfx-config
